## File Reference Table

```{r}
fileReference %>%
  select(fileid, newScenarioName, scenario, path) %>%
  # WORKAROUND:
  # Windows file paths may contain backslashes.
  # But knitr::kable(x, "html"), which will be called by kbl() below,
  # does not handle backslashes well. => Replace them with forward slashes.
  mutate(path = str_replace_all(path, fixed("\\"), "/")) %>%
  kbl(
    booktabs = TRUE,
    col.names = c("ID", "Name Used Here", "Original Name", "Path")) %>%
  kable_styling(
    bootstrap_options = c("condensed"),
    latex_options = c("HOLD_position")) %>%
  column_spec(1:4, background = bkgndColors) %>%
  column_spec(2:3, width = "5.5cm") %>%
  column_spec(4, width = "15.5cm")
```

```{r results='asis'}
cat(
  "\"Historical\" data is taken from ",
  str_replace_all(params$mifHist, fixed("\\"), "/"),
  ".\n\n")
```

```{r results='asis'}
# If a validation config is given in the parameter validationConfig, report
# which config was used and how many threshold bands were computed by the
# preprocessing of the project library (see option mip.validationThresholds).
# For configs listed in validationConfigDocs, a link to the rendered config
# documentation on the piamValidation website is added in a separate row.
validationConfigDocs <- c(
  AMT = "https://pik-piam.github.io/piamValidation/articles/configs/validationConfig_REMIND.html")

if (!is.null(params$validationConfig)) {
  if (file.exists(params$validationConfig)) {
    cfgText <- paste0(
      "`", str_replace_all(params$validationConfig, fixed("\\"), "/"), "`")
  } else {
    cfgText <- paste0("`validationConfig_", params$validationConfig, ".csv`")
  }
  validationThresholds <- getOption("mip.validationThresholds")
  if (is.null(validationThresholds) || nrow(validationThresholds) == 0) {
    cat(
      "No validation thresholds could be computed from the validation config ",
      cfgText, ". Line plots do not show threshold bands, see the rendering ",
      "log for warnings.\n\n", sep = "")
  } else {
    cat(
      "Line plots show validation thresholds from the validation config ",
      cfgText, " as colored background bands where variable, unit, region ",
      "and period match the plotted data (",
      length(unique(validationThresholds$variable)), " variables, ",
      nrow(validationThresholds), " variable-region-period combinations).\n\n",
      sep = "")
  }
  if (params$validationConfig %in% names(validationConfigDocs)) {
    cat(
      "Config documentation: <",
      validationConfigDocs[[params$validationConfig]], ">\n\n", sep = "")
  }
}
```


```{r results='asis'}
# If paths to config files are provided in the parameter cfgScen, their
# content is written to the objects cfgGms and cfgTopLevel in cs2main.Rmd. Here
# and in the next chunks, relevant parts of these configs are displayed.

# Show cfgTopLevel$description (originally cfg$description).
if (exists("cfgTopLevel") && !is.null(cfgTopLevel)) {

  cat("## Descriptions\n\n")

  for (i in 1:max(fileReference$fileid)) {
    cat("### ", as.character(fileReference$newScenarioName[i]), "\n\n")

    description <-
      cfgTopLevel %>%
      filter(fileid == i, name == "description") %>%
      pull(value) %>%
      pluck(1)
    cat(description, "\n\n")
  }
}
```

\newpage
